# Prod Override Values for my Helm Chart

backend:
  replicaCount: 2
  container:
    image: elsergo/django-empty-project:v1
    containerPort: 8000
  ingress:
    host: "empty.home.sergeysidorenko.com"
    path: "/"

nginx:
  replicaCount: 3
  container:
    image: nginx:1.24.0
    containerPort: 80
  ingress:
    host: "empty.home.sergeysidorenko.com"
    path: "/"
