# Prod Override Values for my Helm Chart

backend:
  replicaCount: 1
  container:
    image: docker-hosted.nexus.home.sergeysidorenko.com/1color/backend:v1
    containerPort: 8000
  ingress:
    host: "1color.home.sergeysidorenko.com"
    path: "/"

nginx:
  replicaCount: 1
  container:
    image: nginx:1.24.0
    containerPort: 80
  ingress:
    host: "1color.home.sergeysidorenko.com"
    path: "/static"
