apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  labels:
    app: {{ .Release.Name }}-backend
    owner: SergeySidorenko
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.container.image }}
          command:
            - sh
            - -c
            - nohup gunicorn --workers=5 --threads 2 --timeout 60 --bind=0.0.0.0:8000 onecolor.wsgi:application
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_SECRET_KEY
            - name: DJANGO_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_DOMAIN
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_SUPERUSER_PASSWORD
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_PROFILE
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_PROFILE
            - name: DJANGO_EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_EMAIL_HOST_USER
            - name: DJANGO_EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-env
                  key: DJANGO_EMAIL_HOST_PASSWORD
          ports:
            - containerPort: {{ .Values.backend.container.containerPort }}
      imagePullPolicy: Always
      imagePullSecrets:
        - name: nexus-registry-credential
