apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-credential
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaG9zdGVkLm5leHVzLmhvbWUuc2VyZ2V5c2lkb3JlbmtvLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJMUWVzVE1SYVJYYU1ERDh0aTIkc0JEVEV1cW5LOTIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUub3JnIiwiYXV0aCI6IllXUnRhVzQ2VEZGbGMxUk5VbUZTV0dGTlJFUTRkR2t5SkhOQ1JGUkZkWEZ1U3preSJ9fX0=

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-env
data:
  DJANGO_SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWVwejQ1Yno0ZHVkMTQ4czB2c2psXmFxKjkqenRheEBiaCVid3RjJGdidmVqLXFyNmRy
  DJANGO_DOMAIN: 1color.home.sergeysidorenko.com
  DJANGO_SUPERUSER_USERNAME: YWRtaW4=
  DJANGO_SUPERUSER_PASSWORD: YnU0YWlzMm9vR2gwRWV3YWhy
  DJANGO_SUPERUSER_EMAIL: sergik.sergick@yandex.ru
  DJANGO_PROFILE: local
  DJANGO_EMAIL_HOST_USER: aW5mb0AxY29sb3Iuc3BhY2U=
  DJANGO_EMAIL_HOST_PASSWORD: ZWxlY3Ryb3Nlcmdv