apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-credential
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItaG9zdGVkLm5leHVzLmhvbWUuc2VyZ2V5c2lkb3JlbmtvLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJMUWVzVE1SYVJYYU1ERDh0aTIkc0JEVEV1cW5LOTIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUub3JnIiwiYXV0aCI6IllXUnRhVzQ2VEZGbGMxUk5VbUZTV0dGTlJFUTRkR2t5SkhOQ1JGUkZkWEZ1U3preSJ9fX0=
