apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  labels:
    app: {{ .Release.Name }}-backend
    project: {{ .Release.Name }}
    owner: SergeySidorenko
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - name: {{ .Release.Name }}-backend-listener
      protocol: TCP
      port: {{ .Values.backend.container.containerPort }}  # Port on Load Balancer
      targetPort: {{ .Values.backend.container.containerPort }}  # Port in POD
