apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-credential
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJkb2NrZXItaG9zdGVkLm5leHVzLmhvbWUuc2VyZ2V5c2lkb3JlbmtvLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJMUWVzVE1SYVJYYU1ERDh0aTIiLCJlbWFpbCI6InNlcmdpay5zZXJnaWNrQHlhbmRleC5ydSIsImF1dGgiOiJZV1J0YVc0NlRGRmxjMVJOVW1GU1dHRk5SRVE0ZEdreSJ9fX0=
