apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1color
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: 1color
  source:
    path: "HelmCharts/1color"
    repoURL: "git@github.com:elsergo/1color.git"
    targetRevision: release
    helm:
      valueFiles:
        - values_prod.yaml
      parameters:
        - name: "container.image"
          value: docker-hosted.nexus.home.sergeysidorenko.com/1color/backend:v1

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
