#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: {{ .Release.Name }}-backend-ingress
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: {{ .Values.nginx.ingress.host }}
#    http:
#      paths:
#        - path: {{ .Values.backend.ingress.path }}
#          pathType: Prefix
#          backend:
#            service:
#              name: {{ .Release.Name }}-backend-service
#              port:
#                number: {{ .Values.backend.container.containerPort }}
