apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deployment
  labels:
    app: {{ .Release.Name }}-nginx
    owner: SergeySidorenko
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.container.image }}
          ports:
            - containerPort: {{ .Values.nginx.container.containerPort }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf