apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.nginx.ingress.host }}
    http:
      paths:
        - path: {{ .Values.nginx.ingress.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-nginx
              port:
                number: {{ .Values.nginx.container.containerPort }}
