apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  labels:
    owner: SergeySidorenko
    app: {{ .Release.Name }}-nginx
spec:
  selector:
    app: {{ .Release.Name }}-nginx
    project: {{ .Release.Name }}    # Selecting PODS with those Labels
  ports:
    - name: {{ .Release.Name }}-nginx-listener
      protocol: TCP
      port: {{ .Values.nginx.container.containerPort }}  # Port on Load Balancer
      targetPort: {{ .Values.nginx.container.containerPort }}  # Port in POD
